minghtml/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/retsigers/', views.register, name='register'),
    
]

minghtml/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('share125vjr/', views.cyut, name='cyut'),
    path('version/', views.version, name='version'),
    path('connection/', views.connection, name='connection'),
    path('download/', views.download, name='download')
]

minghtml/minghtml/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),   
]

minghtml/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    fullName = models.CharField(max_length=128)
    

    def __str__(self):
        return self.fullName 

minghtml/main/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=128)
    content = models.TextField()

    def __str__(self):
        return self.title

minghtml/account/forms.py
from django import forms
from account.models import User

class UserForm(forms.ModelForm):
    fullName = forms.CharField(label='全名姓名', max_length=128)
    username = forms.CharField(label='帳號')
    password = forms.CharField(label='密碼', widget=forms.PasswordInput())
    password2 = forms.CharField(label='確認密碼', widget=forms.PasswordInput())
   
    
    class Meta:
        model = User
        fields = ['fullName','username','password', 'password2']

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password!=password2:
            raise forms.ValidationError('密碼不相符')
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(user.password)
        if commit:
            user.save()
        return user

minghtml/main/forms.py
from django import forms
from main.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='功課', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']

minghtml/account/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from account.forms import UserForm

def register(request):
    template = 'account/register.html'
    if request.method == 'GET':
        return render(request, template, {'userForm':UserForm()})

    # POST
    userForm = UserForm(request.POST)
    if not userForm.is_valid():
        return render(request, template, {'userForm':userForm})

    userForm.save()
    messages.success(request, '歡迎註冊')
    return redirect('main:main')

def login(request):
    template = 'account/login.html'
    if request.method == 'GET':
        return render(request, template, {'nextURL':request.GET.get('next')})

    username = request.POST.get('username')
    password = request.POST.get('password')
    if not username or not password:    # Server-side validation
        messages.error(request, '請填資料')
        return render(request, template)

    user = authenticate(username=username, password=password)
    if not user:    # authentication fails
        messages.error(request, '登入失敗')
        return render(request, template)

    # login success
    auth_login(request, user)
    nextURL = request.POST.get('nextURL')
    if nextURL:
        return redirect(nextURL)
    messages.success(request, '登入成功')
    return redirect('main:main')

def logout(request):
    auth_logout(request)
    messages.success(request, '歡迎再度光臨')
    return redirect('main:main')

minghtml/main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls.base import reverse
from main.models import Article
from main.forms import ArticleForm

def main(request):
    return render(request,'main/main.html')

def cyut(request):
    articles = Article.objects.all()
    context = {'articles':articles}
    return render(request,'main/cyut.html', context)

def version(request):
    return render(request,'main/version.html')

def connection(request):
    return render(request,'main/connection.html')

def download(request):
    return render(request,'main/download.html')

def admin_required(func):
    def auth(request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(request, '請以管理者身份登入')
            return redirect(reverse('account:login') + '?next=' + request.get_full_path())
        return func(request, *args, **kwargs)
    return auth

minghtml/main/templates/main/computer.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
	<title>保齡球連結網站</title>
	<meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/div.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/two.css' %}">
    <style>
/* Basic Reset */
* {
	border: none;
	font-family: 'Open Sans', sans-serif;
	margin: 0;
	padding: 0;
}
body {

}
.center {
	background-color: #fff;
	border-radius: 50%;
	height: 600px;
	margin: auto;
	width: 600px;
}
h1 {
	color: #495678;
	font-size: 30px;	
	margin-top: 20px;
	padding-top: 50px;
	display: block;
	text-align: center;
	text-decoration: none;
}
a {
	color: #495678;
	font-size: 30px;	
	display: block;
	text-align: center;
	text-decoration: none;
	padding-top: 20px;
}
form {
	background-color: #495678;
	box-shadow: 4px 4px #3d4a65;
	margin: 40px auto;
	padding: 40px 0 30px 40px;	
	width: 280px;
}
.btn {
	outline: none;
	cursor: pointer;
	font-size: 20px;
	height: 45px;
	margin: 5px 0 5px 10px;
	width: 45px;
}
.btn:first-child {
	margin: 5px 0 5px 10px;
}
.btn, #display, form {
	border-radius: 25px;
}
#display {
	outline: none;
	background-color: #98d1dc;
	box-shadow: inset 6px 6px 0px #3facc0;
	color: #dededc;
	font-size: 20px;
	height: 47px;
	text-align: right;
	width: 165px;
	padding-right: 10px;
	margin-left: 10px;
}
.number {
	background-color: #72778b;
	box-shadow: 0 5px #5f6680;
	color: #dededc;
}
.number:active {
	box-shadow: 0 2px #5f6680;
  	-webkit-transform: translateY(2px);
  	-ms-transform: translateY(2px);
  	-moz-tranform: translateY(2px);
  	transform: translateY(2px);
}
.operator {
	background-color: #dededc;
	box-shadow: 0 5px #bebebe;
	color: #72778b;
}
.operator:active {
	box-shadow: 0 2px #bebebe;
  	-webkit-transform: translateY(2px);
  	-ms-transform: translateY(2px);
  	-moz-tranform: translateY(2px);
  	transform: translateY(2px);
}
.other {
	background-color: #e3844c;
	box-shadow: 0 5px #e76a3d;
	color: #dededc;
}
.other:active {
	box-shadow: 0 2px #e76a3d;
  	-webkit-transform: translateY(2px);
  	-ms-transform: translateY(2px);
  	-moz-tranform: translateY(2px);
  	transform: translateY(2px);
}
</style>
</head>
<body>
  <div id='all'>

    <div class="center">
		<form name="calculator">
			<input type="button" id="clear" class="btn other" value="C">
			<input type="text" id="display">
				<br>
			<input type="button" class="btn number" value="7" onclick="get(this.value);">
			<input type="button" class="btn number" value="8" onclick="get(this.value);">
			<input type="button" class="btn number" value="9" onclick="get(this.value);">
			<input type="button" class="btn operator" value="+" onclick="get(this.value);">
				<br>
			<input type="button" class="btn number" value="4" onclick="get(this.value);">
			<input type="button" class="btn number" value="5" onclick="get(this.value);">
			<input type="button" class="btn number" value="6" onclick="get(this.value);">
			<input type="button" class="btn operator" value="*" onclick="get(this.value);">
				<br>
			<input type="button" class="btn number" value="1" onclick="get(this.value);">
			<input type="button" class="btn number" value="2" onclick="get(this.value);">
			<input type="button" class="btn number" value="3" onclick="get(this.value);">
			<input type="button" class="btn operator" value="-" onclick="get(this.value);">
				<br>
			<input type="button" class="btn number" value="0" onclick="get(this.value);">
			<input type="button" class="btn operator" value="." onclick="get(this.value);">
			<input type="button" class="btn operator" value="/" onclick="get(this.value);">			
			<input type="button" class="btn other" value="=" onclick="calculates();">
		</form>
	</div>
  </div>
 </body>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script>
	/* limpa o display */ 
document.getElementById("clear").addEventListener("click", function() {
	document.getElementById("display").value = "";
});
/* recebe os valores */
function get(value) {
	document.getElementById("display").value += value; 
} 

/* calcula */
function calculates() {
	var result = 0;
	result = document.getElementById("display").value;
	document.getElementById("display").value = "";
	document.getElementById("display").value = eval(result);
};
	</script>
</html>

minghtml/main/templates/main/connection.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
	<title>保齡球連結網站</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'main/css/div.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/account.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/two.css' %}">
</head>
<body>
  <div id='all'>
    <div id='header'>
    {% include 'other/head.html' %}
	</div>
  	<div id='center'>
  		<table style='margin-left:auto;	margin-right:auto;'>
	  	  <tr><td class='contd1' colspan='2'>版主訊息</td></tr>
	  	  <tr><td class='contdtitle'>NAME:<td class='contd'>BoMing-Liao</td></tr>
	  	  <tr><td class='contdtitle'>E-mail:<td class='contd'>a0918891539@gmail.com</td></tr>
	  	  <tr><td class='contdtitle'><td class='contd'>s10614150@cyut.edu.tw</td></tr>
	  	  <tr><td class='contdtitle'>School:<td class='contd'>Chaoyang University of Technology</td></tr>
	  	  <tr><td class='contdtitle'><td class='contd'>CYUT</td></tr>
	  	  <tr><td class='contdtitle'>Departmant:<td class='contd'>Information management department 2C</td></tr>
	  	  <tr><td class='contd1' colspan='2'>*Thanks*</td></tr>
	  	</table>
	  	<p>
  	</div>
  <div id='footer'>
      {% include 'other/footer.html' %}
  </div>
  </div>
 </body>
</html>

minghtml/main/templates/main/download.html
<!doctype html>
{% load staticfiles %}
<html>
   <head>
      <title>保齡球連結網站</title>
      <meta charset="utf-8">
      <link rel="stylesheet" href="{% static 'main/css/div.css' %}">
      <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
      <link rel="stylesheet" href="{% static 'main/css/two.css' %}">
	  <style>
	  .td_style{
		text-align: left; 
		padding: 2px 0px 6px 5px; 
		font-size:25px;
	  }
	</style>
   </head>
   <body>
      <div id='all'>
	      <div id='header'>
			{% include 'other/head.html' %}
		  </div>
         <div class="center">
            <table class='tab'>
               <tr>
                  <td class="td_style"><a href="https://rar.tw/download.html" target="_blank"><img class="image" src="{% static 'main/img1/WinRAR.png' %}"> WinRAR</a></td>
                  <td class="td_style"><a href="https://www.developershome.com/7-zip/" target="_blank"><img class="image" src="{% static 'main/img1/7zip.png' %}"> 7-zip</a></td>
               </tr>
               <tr>
                  <td class="td_style"><a href="https://get.adobe.com/tw/reader/" target="_blank"><img class="image" src="{% static 'main/img1/acrobat_dc.png' %}"> Reader DC</a></td>
                  <td class="td_style"><a href="https://notepad-plus-plus.org/downloads/" target="_blank"><img class="image" src="{% static 'main/img1/Notepad++.png' %}"> Notepad++</a></td>
                  
               </tr>
               <tr>
                  <td class="td_style"><a href="https://www.teamviewer.com/tw/download/windows/" target="_blank"><img class="image" src="{% static 'main/img1/teamviewer.png' %}"> TeamViewer</a></td>
                  <td class="td_style"><a href="https://anydesk.com/zhs" target="_blank"><img class="image" src="{% static 'main/img1/anydesk.png' %}"> Anydesk</a></td>
                  
               </tr>
               <tr>
                  <td class="td_style"><a href="https://visualstudio.microsoft.com/zh-hant/downloads/" target="_blank"><img class="image" src="{% static 'main/img1/visualstudio.png' %}"> Visual Studio</a></td>
                  <td class="td_style"><a href="https://code.visualstudio.com/" target="_blank"><img class="image" src="{% static 'main/img1/vscode.png' %}"> Visual Code</a></td>
               </tr>
               <tr>
                  <td class="td_style"><a href="https://www.python.org/" target="_blank"><img class="image" src="{% static 'main/img1/python.png' %}"> Python</a></td>
                  <td class="td_style"><a href="https://java.com/zh_TW/download/" target="_blank"><img class="image" src="{% static 'main/img1/java.png' %}"> Java</a></td>
               </tr>
               <tr>
                  <td class="td_style"><a href="http://brackets.io/" target="_blank"><img class="image" src="{% static 'main/img1/Brackets.png' %}"> Brackets</a></td>
                  <td class="td_style"><a href="https://www.anaconda.com/distribution/" target="_blank"><img class="image" src="{% static 'main/img1/anaconda.png' %}"> Anaconda</a></td>
               </tr>
               <tr>
                  <td class="td_style"><a href="https://www.eclipse.org/downloads/" target="_blank"><img class='image' src="{% static 'main/img1/eclipse.png' %}"> Eclipse</a></td>
                  <td class="td_style"><a href="https://netbeans.org/downloads/8.0.2/" target="_blank"><img class='image' src="{% static 'main/img1/netbeans.png' %}"> Netbeans</a></td>
               </tr>
               <tr>
                  <td class="td_style"><a href="https://docs.microsoft.com/zh-tw/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017" target="_blank"><img class='image' src="{% static 'main/img1/ssms.png' %}"> SSMS</a></td>
                  <td class="td_style"><a href="https://www.oracle.com/technetwork/developer-tools/sql-developer/downloads/index.html" target="_blank"><img class="image" src="{% static 'main/img1/sqldev.png' %}">SQL Developer</a></td>
               </tr>
               <tr>
                  <td class="td_style"><a href="https://www.apachefriends.org/zh_tw/index.html" target="_blank"><img class='image' src="{% static 'main/img1/xampp.png' %}"> XAMPP</a></td>
               </tr>
               <tr>
                  <td class="td_style" colspan="2"><a href="https://www.microsoft.com/zh-tw/sql-server/sql-server-downloads" target="_blank"><img class='image' src="{% static 'main/img1/microsoftSQL.png' %}"> Microsoft SQL Sever</a></td>
               </tr>
            </table>
         </div>
		   <div id='footer'>
			{% include 'other/footer.html' %}
		   </div>
      </div>
   </body>
</html>

minghtml/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
	<title>保齡球連結網站</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'main/css/div.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/account.css' %}">
</head>
<body>
  <div id='all'>
    <div id='header'>
    {% include 'other/head.html' %}
    </div>
	  <div id='left'>
		{% include 'other/mainleft.html' %}
	  </div>
	  <div id='center'>
		{% include 'other/maincenter.html' %}
	  </div>
	  <div id='right'>
		{% include 'other/mainright.html' %}
	  </div>
  <div id='footer'>
      {% include 'other/footer.html' %}
  </div>
  </div>
 </body>
</html>

minghtml/main/templates/main/version.html
<!doctype html>
{% load staticfiles %}
<html>
<head> 
	<title>保齡球連結網站</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'main/css/div.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/account.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/two.css' %}">
</head>
<body>
  <div id='all'>
    <div id='header'>
    {% include 'other/head.html' %}
	</div>
  	  <div id='verleft'> 
	  	<table style='margin-left:auto;margin-right:auto;'>
	  	  <tr><td class='ver_td' colspan='3'>版本資訊(大版)</td></tr>
	  	  <tr><td class='ver_title'>Ver</td> <td class='ver_title'>Online-Date(2019)</td> <td class='ver_title' style='width:400px;'>content</td></tr>
	  	  <tr><td class='ver_td'>1.0版</td> <td class='ver_td'>02月08日</td> <td class='ver_con'>出版上線 伺服器連線測試</td></tr>
	  	  <tr><td class='ver_td'>1.5版</td> <td class='ver_td'>02月22日</td> <td class='ver_con'>正式公開上線、修改網頁連結功能</td></tr>
	  	  <tr><td class='ver_td'>2.0版</td> <td class='ver_td'>03月11日</td> <td class='ver_con'>增加後端存取功能</td></tr>
	  	  <tr><td class='ver_td'>2.5版</td> <td class='ver_td'>04月14日</td> <td class='ver_con'>簡化程式內容</td></tr>
	  	</table>
	 </div>
	 <div id='verright'>
	  	<table style='margin-left:auto;margin-right:auto;'>
	  	  <tr><td class='ver_td' colspan='3'>版本資訊(小版)</td></tr>
	  	  <tr><td class='ver_title'>Ver</td> <td class='ver_title'>Online-Date</td> <td class='ver_title' style='width:400px;'>content</td></tr>
	  	  <tr><td class='ver_td'>1.3版</td> <td class='ver_td'>02月11日</td> <td class='ver_con'>提供註冊、新增版本資訊、聯絡版主</td></tr>
	  	  <tr><td class='ver_td'>1.8版</td> <td class='ver_td'>03月09日</td> <td class='ver_con'>功課專區、資訊專區</td></tr>
	  	  <tr><td class='ver_td'>2.3版</td> <td class='ver_td'>04月02日</td> <td class='ver_con'>修改網頁</td></tr>
	  	  <tr><td class='ver_td'>3.0版</td> <td class='ver_td'>06月28日</td> <td class='ver_con'>關閉後端登入資訊</td></tr>
	  	</table>	
  	</div>
  <div id='footer'>
      {% include 'other/footer.html' %}
  </div>
  </div>
 </body>
</html>

minghtml/main/templates/other/footer.html
<table style='float:left;width:400px;'>
  <tr><td><font size="5"><b>Ver 5.0</b></font></td></tr>
  <tr><td><font size="3">公布日期：2021年4月09日</font></td></tr>
  <tr><td></td></tr>
</table>

{% for message in messages %}
  <font style='color:#00ffff;font-size:30px;' class="{{ message.tags }}">{{ message }}</font>
{% endfor %}

minghtml/main/templates/other/head.html
{% load staticfiles %}
<table style="width:100%">
  <tr>
	<td style="text-align: center;"><a href="{% url 'main:main' %}"><font style="color: #ffffff;"><h1>保齡球連結網站</h1></font></a></td>
  </tr>
</table>

minghtml/main/templates/other/maincenter.html
{% load staticfiles %}
<style>
  .td_style{
  	text-align: left; 
	  padding: 2px 0px 6px 5px; 
	  font-size:25px;
  }
</style>
<br>
<table class='tab'>
  <tr><td class="td_style"><a href="https://www.railway.gov.tw/tra-tip-web/tip" target="_blank"><img class="image" src="{% static 'main/img/taiwan_train.png' %}" title="臺鐵"> 台鐵首頁</a></td></tr>
  <tr><td class="td_style"><a href="https://www.railway.gov.tw/tra-tip-web/tip/tip001/tip112/gobytime" target="_blank"><img class="image" src="{% static 'main/img/taiwan_train.png' %}" title="臺鐵"> 時刻表查詢</a></td></tr>
  <tr><td class="td_style"><a href="https://www.railway.gov.tw/tra-tip-web/tip/tip001/tip119/queryTime" target="_blank"><img class="image" src="{% static 'main/img/taiwan_train.png' %}" title="臺鐵"> 列車剩餘車票</a></td></tr>
</table>
<br>
<table class='tab'>
  <tr><td class="td_style"><a href="https://www.thsrc.com.tw/index.html" target="_blank"><img class="image" src="{% static 'main/img/high_train.png' %}" title="高鐵"> 高鐵首頁</a></td></tr>
  <tr><td class="td_style"><a href="https://irs.thsrc.com.tw/IMINT/" target="_blank"><img class="image" src="{% static 'main/img/high_train.png' %}" title="高鐵"> 網路訂票</a></td></tr>
  <tr><td class="td_style"><a href="https://www.thsrc.com.tw/tw/TimeTable/SearchResult" target="_blank"><img class="image" src="{% static 'main/img/high_train.png' %}" title="高鐵"> 時刻表與票價查詢</a></td></tr>
</table>
<br>
<table class='tab'>
  <tr><td class="td_style"><a href="https://shopee.tw/" target="_blank"><img class='image' src="{% static 'main/img/shopee.png' %}" title='蝦皮購物'> 蝦皮購物</a></td></tr>
  <tr><td class="td_style"><a href="https://www.ruten.com.tw/" target="_blank"><img class='image' src="{% static 'main/img/ruten.png' %}" title='露天購物'> 露天購物</a></td></tr>
  <tr><td class="td_style"><a href="https://tw.mall.yahoo.com/" target="_blank"><img class='image' src="{% static 'main/img/yahoo.png' %}" title='Yahoo商城'> Yahoo商城</a></td></tr>
  <tr><td class="td_style"><a href="https://shopping.pchome.com.tw/" target="_blank"><img class='image' src="{% static 'main/img/pchome.png' %}" title='PChome'> PChome</a></td></tr>
</table>
<br>
<table class='tab'>
  <tr><td class="td_style"><a href="https://www.taiwanmobile.com/index.html" target="_blank"><img class='image' src="{% static 'main/img/twnmobile.png' %}" title='台灣大哥大'> 台灣大哥大</a></td></tr>
</table>
<br>

minghtml/main/templates/other/mainright.html
{% load staticfiles %}
<style>
  .td_style{
  	text-align: left; 
	  padding: 2px 0px 6px 5px; 
	  font-size:25px;
  }
</style>
<br>
<table class='tab'>
  <tr>
    <td class="td_style"><a href="http://yltang.net/tutorial/dsml/" target="_blank"><img class="image" src="{% static 'main/img1/dsmllogo.png' %}"> Machine Learning</a></td>
    <td class="td_style"><a href="http://yltang.net/tutorial/webdesign/0/" target="_blank"><img class="image" src="{% static 'main/img1/wdlogo.png' %}"> Web Design</a></td>
  </tr>
  <tr>
    <td class="td_style"><a href="http://yltang.net/tutorial/javascript/0/" target="_blank"><img class="image" src="{% static 'main/img1/jslogo.png' %}"> Javascript</a></td>
    <td class="td_style"><a href="http://yltang.net/django-book/" target="_blank"><img class="image" src="{% static 'main/img1/djangologo.png' %}"> Django</a></td>
  </tr>
  <tr><td colspan="2"><p></p></td></tr>
  <tr>
    <td class="td_style"><a href="https://tv.line.me/" target="_blank"><img class='image' src="{% static 'main/img/line_tv.png' %}" title='line tv'> LINE TV</a></td>
    <td class="td_style"><a href="https://www.kktv.me/" target="_blank"><img class='image' src="{% static 'main/img/kktv.png' %}" title='kktv'> KKTV</a></td>
  </tr>
  <tr>
    <td class="td_style"><a href="http://tw.iqiyi.com/dianying/" target="_blank"><img class='image' src="{% static 'main/img/QIY.png' %}" title='愛奇藝' width='70px'> 愛奇藝</a></td>
    <td class="td_style"><a href="https://www.litv.tv/" target="_blank"><img class='image' src="{% static 'main/img/litv.png' %}" title='Litv'> LiTV</a></td>
  </tr>
  <tr>
    <td class="td_style"><a href="http://www.99kubo.tv/" target="_blank">99酷播</a></td>
    <td class="td_style"><a href="http://dramasq.com/" target="_blank">DramasQ線上看</a></td>
  </tr>
  <tr><td colspan="2"><p></p></td></tr>
  <tr>
    <td class="td_style" colspan="2"><a href="{% url 'main:download' %}" target="_blank">軟體安裝下載→→→</a></td>
  </tr>
</table>